/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FeatherIcon {
        "name": string;
        "size": string;
    }
    interface FeatherSprite {
        "name": string;
        "size": string;
    }
}
declare global {
    interface HTMLFeatherIconElement extends Components.FeatherIcon, HTMLStencilElement {
    }
    var HTMLFeatherIconElement: {
        prototype: HTMLFeatherIconElement;
        new (): HTMLFeatherIconElement;
    };
    interface HTMLFeatherSpriteElement extends Components.FeatherSprite, HTMLStencilElement {
    }
    var HTMLFeatherSpriteElement: {
        prototype: HTMLFeatherSpriteElement;
        new (): HTMLFeatherSpriteElement;
    };
    interface HTMLElementTagNameMap {
        "feather-icon": HTMLFeatherIconElement;
        "feather-sprite": HTMLFeatherSpriteElement;
    }
}
declare namespace LocalJSX {
    interface FeatherIcon {
        "name"?: string;
        "size"?: string;
    }
    interface FeatherSprite {
        "name"?: string;
        "size"?: string;
    }
    interface IntrinsicElements {
        "feather-icon": FeatherIcon;
        "feather-sprite": FeatherSprite;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "feather-icon": LocalJSX.FeatherIcon & JSXBase.HTMLAttributes<HTMLFeatherIconElement>;
            "feather-sprite": LocalJSX.FeatherSprite & JSXBase.HTMLAttributes<HTMLFeatherSpriteElement>;
        }
    }
}
